name: Deploy to Locaweb

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Locaweb
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ftp.aesaonline.com.br
          username: aesaonline1
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './*'
          remote_path: '/home/aesaonline/public_html/' 